platform: linux

image_resource:
  type: docker-image
  source: { repository: alpine }

outputs:
  - name: values

params:
  RELEASE_NAME: ((release_name))

run:
  path: ash
  args:
    - -c
    - |
      set -o errexit -o nounset -o xtrace
      cat > values/db.yaml <<EOF
      db:
        host: ${RELEASE_NAME}-postgresql
        password: mysecretpassword
      EOF
