platform: linux

image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: latest

inputs:
  - name: pay-gsp
  - name: endtoend-image
  - name: stubs-image
  - name: demo-service-image

outputs:
  - name: pay-gsp

run:
  path: bash
  args:
    - -xc
    - |
      set -o errexit -o nounset -o pipefail

      repo() {
        local repository=$(cat "$1/repository")
        echo "${repository}@sha256:"
      }

      ref() {
        cat "$1/digest"
      }

      cat > new_values.yaml <<EOF
      endtoend:
        image:
          repository: "$(repo endtoend-image)"
          tag: "$(ref endtoend-image)"
      demoService:
        image:
          repository: "$(repo demo-service-image)"
          tag: "$(ref demo-service-image)"
      stubs:
        image:
          repository: "$(repo stubs-image)"
          tag: "$(ref stubs-image)"
      EOF

      spruce merge pay-gsp/charts/stubs/values.yaml new_values.yaml > tmp
      tee pay-gsp/charts/stubs/values.yaml < tmp
