platform: linux

image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: latest

inputs:
  - name: pay-gsp
  - name: adminusers-image
  - name: cardid-image
  - name: connector-image
  - name: dd-connector-image
  - name: dd-frontend-image
  - name: frontend-image
  - name: ledger-image
  - name: products-image
  - name: products-ui-image
  - name: publicapi-image
  - name: publicauth-image
  - name: selfservice-image
  - name: toolbox-image

outputs:
  - name: pay-gsp

run:
  path: bash
  args:
    - -xc
    - |
      set -o errexit -o nounset -o pipefail

      source "pay-gsp/tasks/functions.sh"

      cat > new_values.yaml <<EOF
      adminUsers:
        image:
          repository: "$(repo adminusers-image)"
          tag: "$(ref adminusers-image)"
      cardID:
        image:
          repository: "$(repo cardid-image)"
          tag: "$(ref cardid-image)"
      connector:
        image:
          repository: "$(repo connector-image)"
          tag: "$(ref connector-image)"
      directDebit:
        connector:
          image:
            repository: "$(repo dd-connector-image)"
            tag: "$(ref dd-connector-image)"
        frontend:
          host:
          image:
            repository: "$(repo dd-frontend-image)"
            tag: "$(ref dd-frontend-image)"
      frontend:
        host:
        image:
          repository: "$(repo frontend-image)"
          tag: "$(ref frontend-image)"
      products:
        image:
          repository: "$(repo products-image)"
          tag: "$(ref products-image)"
        ui:
          host:
          image:
            repository: "$(repo products-ui-image)"
            tag: "$(ref products-ui-image)"
      public:
        api:
          image:
            repository: "$(repo publicapi-image)"
            tag: "$(ref publicapi-image)"
        auth:
          image:
            repository: "$(repo publicauth-image)"
            tag: "$(ref publicauth-image)"
      selfService:
        image:
          repository: "$(repo selfservice-image)"
          tag: "$(ref selfservice-image)"
      EOF

      spruce merge pay-gsp/charts/pay/values.yaml new_values.yaml > tmp
      tee pay-gsp/charts/pay/values.yaml < tmp
