apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-public-api
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Release.Name }}-public-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - {{ include "public.api.host" . }}
  gateways:
  - {{ .Release.Name }}-gateway
  http:
    - route:
      - destination:
          host: {{ .Release.Name }}-public-api
          port:
            number: 80
