apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}-selenium-hub-egress
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - {{ .Release.Name }}-selenium-hub
  ports:
  - name: selenium
    number: 4444
    protocol: TLS
  location: MESH_EXTERNAL
  resolution: DNS
