apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    istio: {{ .Values.global.cluster.name }}-ingressgateway
  servers:
  - hosts:
      {{ template "publicHosts" . }}
      {{ template "stubs.publicHosts" . }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .Release.Name }}-ingress-certificate
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
  - hosts:
      {{ template "publicHosts" . }}
      {{ template "stubs.publicHosts" . }}
    port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
